name: things
description: things

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  scroll_snap_list: ^0.9.1
  flutter_bloc: ^8.1.3
  wheel_chooser: ^1.1.2
  jiffy: ^6.2.1
  dynamic_color: ^1.6.8
  marquee: ^2.2.3
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  build_runner:

  #flutter pub get
  #dart run build_runner build
  flutter_gen_runner: ^5.3.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/activities.json